### PR TITLE
Add call paths to Flog

### PR DESCRIPTION
**Pull request by marcinwyszynski**

### CODE REVIEW

**Comment by zenspider** [comment]
English/style is a bit off. Can you change it to `call_path` so it reads `call_path[signature]`? Thanks!

**Comment by marcinwyszynski** [comment]
Fair enough, I called is `call_paths` instead. I think it's actually a good practice to call collections using plural forms and `Hash` is most certainly a collection of items.

**Comment by zenspider** [comment]
unless the value is an array, the value you get out of it is singular. So `call_path[signature]` reads as `"call path for signature"`.

**Comment by marcinwyszynski** [comment]
OK your gem your rules; PTAL.

**Pull request closed without merging**
